apiVersion: v1
kind: ConfigMap
metadata:
  name: debugmode-k8s-ces-control-activation-1-state
  namespace: default
  labels:
    debugmode.k8s.cloudogu.com/owner: k8s-ces-control-activation-1
  ownerReferences:
    - apiVersion: k8s.cloudogu.com/v1
      kind: DebugMode
      name: k8s-ces-control-activation-1
      uid: <DEBUGMODE-UID>  # vom Controller dynamisch gesetzt
      controller: true
      blockOwnerDeletion: true
data:
  dogu/ldap: INFO
  dogu/cas: WARN
  component/k8s-blueprint-operator: DEBUG
  component/ces-exporter: WARN